test:
  image: golang:1.22.3
  stage: test
  script:
    - go install
    - go test -v

deploy:
  image: node:current
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
  stage: deploy
  script:
    - npm install -g wrangler --unsafe-perm=true
    - wrangler pages deploy --branch=production
