name: Generate a Trunkver
description: Create a TrunkVer for this github action run
author: crftd.tech
branding:
  color: orange
  icon: fast-forward
inputs:
  baseVersion:
    description: The base version to use (only if prerelease is true)
    required: false
    default: ""
  prerelease:
    description: Whether to generate the prerelease part of a SemVer
    required: false
    default: "false"
  increment:
    description: Increment the given part of a base version
    required: false
    default: ""
outputs:
  trunkver:
    description: The TrunkVer
runs:
  using: docker
  image: 'docker://ghcr.io/crftd-tech/trunkver@sha256:7d6b7facedf296cba8d368f23fb1d987e377727073be2115461b46897feae1ec'
  entrypoint: /bin/sh
  args:
    - -xeu
    - -o
    - pipefail
    - -c
    - trunkver --verbose generate "--prerelease=${{ inputs.prerelease }}" "--increment=${{ inputs.increment }}" "--output=${GITHUB_OUTPUT}" "--format=trunkver={{ . }}" "${{ inputs.baseVersion }}"
