name: TrunkVer
description: Create a TrunkVer for this github action run
author: crftd.tech
inputs:
  baseVersion:
    description: The base version to use (only if prerelease is true)
    required: false
    default: ""
  prerelease:
    description: Whether to generate the prerelease part of a SemVer
    required: false
    default: "false"
outputs:
  trunkver:
    description: The TrunkVer
runs:
  using: docker
  image: 'docker://ghcr.io/crftd-tech/trunkver:1.0.0-20240629024432-g4c57b25-9720991314-1'
  entrypoint: /bin/sh
  args:
    - -xeu
    - -o
    - pipefail
    - -c
    - /trunkver generate "--prerelease=${{ inputs.prerelease }}" "--output=${GITHUB_OUTPUT}" "--format=trunkver={{ . }}" "${{ inputs.baseVersion }}"
