name: trunkver
description: Create a trunkver for this github action run
author: crftd.tech
inputs:
  baseVersion:
    description: The base version to use
    required: false
    default: ""
  prerelease:
    description: The prerelease version to use
    required: false
    default: "false"
outputs:
  trunkver:
    description: The trunkver
runs:
  using: docker
  image: docker://ghcr.io/crftd-tech/trunkver:20240525151039.0.0-g6e81b46-9236367679
  entrypoint: /bin/sh
  args:
    - -eu
    - -o
    - pipefail
    - -c
    - echo trunkver=$(/trunkver "--prerelease=${{ inputs.prerelease }}" "${{ inputs.baseVersion }}") | tee $GITHUB_OUTPUT
