name: Test Workflow

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run another action
        id: trunkver
        uses: crftd-tech/trunkver@main
      - name: Print trunkver
        run: echo "The trunkver is ${{ steps.trunkver.outputs.trunkver }}"